### CREATE A NEW COSTUMER
POST http://localhost:8080/foodserver/api/costumers
Content-Type: application/json

{
  "name": "bruno",
  "mobilePhone": "459999999",
  "email": "bruno.imai@pucpr.edu.br",
  "password": "123",
  "orders": [],
  "roles": []
}


### CREATE A NEW RESTAURANT
POST http://localhost:8080/foodserver/api/restaurant
Content-Type: application/json

{
  "name": "Restaurante Admin",
  "email": "batata@email",
  "password": "senha12345678",
  "roles": ["ADMIN"],
  "restaurantImage" : "umaImagem.jpg"
}

###ADD PRODUCT 1
POST http://localhost:8080/foodserver/api/restaurant/1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODczMDU2MDAsImV4cCI6MTY4NzQ3ODQwMCwiaXNzIjoiRm9vZDJHb1NlcnZlciIsInN1YiI6IjEiLCJyZXN0YXVyYW50SWQiOjEsInJlc3RhdXJhbnQiOnsiaWQiOjEsImVtYWlsIjoiYmF0YXRhQGVtYWlsIiwibm9tZSI6IlJlc3RhdXJhbnRlIEFkbWluIiwicm9sZXMiOlsiQURNSU4iXX19.zMoW-TYqRw0T12WbWIEDIpqwTpQoNlDgtBhf4UUjuGE

{
  "name": "x queijo",
  "price": 16.90,
  "description": "pao carne queijo",
  "productImage": "umaImagem.jpg"
}

###ADD PRODUCT 2
POST http://localhost:8080/foodserver/api/restaurant/1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODczMDU2MDAsImV4cCI6MTY4NzQ3ODQwMCwiaXNzIjoiRm9vZDJHb1NlcnZlciIsInN1YiI6IjEiLCJyZXN0YXVyYW50SWQiOjEsInJlc3RhdXJhbnQiOnsiaWQiOjEsImVtYWlsIjoiYmF0YXRhQGVtYWlsIiwibm9tZSI6IlJlc3RhdXJhbnRlIEFkbWluIiwicm9sZXMiOlsiQURNSU4iXX19.zMoW-TYqRw0T12WbWIEDIpqwTpQoNlDgtBhf4UUjuGE

{
  "name": "x linguiça",
  "price": 14.90,
  "description": "pao linguiça queijo",
  "productImage": "umaImagem.jpg"
}

###ADD PRODUCT 3
POST http://localhost:8080/foodserver/api/restaurant/1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODczMDU2MDAsImV4cCI6MTY4NzQ3ODQwMCwiaXNzIjoiRm9vZDJHb1NlcnZlciIsInN1YiI6IjEiLCJyZXN0YXVyYW50SWQiOjEsInJlc3RhdXJhbnQiOnsiaWQiOjEsImVtYWlsIjoiYmF0YXRhQGVtYWlsIiwibm9tZSI6IlJlc3RhdXJhbnRlIEFkbWluIiwicm9sZXMiOlsiQURNSU4iXX19.zMoW-TYqRw0T12WbWIEDIpqwTpQoNlDgtBhf4UUjuGE

{
  "name": "pao com bolinho",
  "price": 14.90,
  "quantity": 50,
  "description": "pao quibe queijo tomate",
  "productImage": "umaImagem.jpg"
}

###CREATE ORDER
POST http://localhost:8080/foodserver/api/costumers/order/1/1
Content-Type: application/json

{
  "name": "EM ANDAMENTO",
  "products": [1,2,3]
}

### LOGIN
POST http://localhost:8080/foodserver/api/restaurant/login
Content-Type: application/json

{
  "email": "batata@email",
  "password": "senha12345678"
}

### DELETE RESTAURANT ID 1
DELETE http://localhost:8080/foodserver/api/restaurant/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODczMDU2MDAsImV4cCI6MTY4NzQ3ODQwMCwiaXNzIjoiRm9vZDJHb1NlcnZlciIsInN1YiI6IjEiLCJyZXN0YXVyYW50SWQiOjEsInJlc3RhdXJhbnQiOnsiaWQiOjEsImVtYWlsIjoiYmF0YXRhQGVtYWlsIiwibm9tZSI6IlJlc3RhdXJhbnRlIEFkbWluIiwicm9sZXMiOlsiQURNSU4iXX19.zMoW-TYqRw0T12WbWIEDIpqwTpQoNlDgtBhf4UUjuGE

